version: '3'
services:
    app:
        container_name: help-desk-backend
        image: ghornon/help-desk-backend
        restart: always
        build: ./
        ports:
            - '8080:8080'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - '27017:27017'
